app_data/sheets/contents.json
app_data/sheets/template/app_menu.json
app_data/sheets/template/component_demo/comp_qr_code.json
app_data/sheets/template/component_demo/comp_select_text.json
app_data/sheets/template/home_screen.json
config.ts

content: 1.1.6

---

.github/workflows/app-build.yml
.github/workflows/deploy-firebase.yml
config.ts

- Add App Build action
- Add Deploy to Firebase action

ci: Add build and firebase deploy actions

---

app_data/sheets/template/component_demo/comp_task_card.json
config.ts

Update `comp_task_card` template

content: 1.1.17

---

app_data/sheets/template/debug/example_calc_substring.json
config.ts

- add example for checking whether a list includes an entry

content: 1.1.27

---

app_data/sheets/template/component_demo/feat_animated_slides.json
config.ts

- content sync to trigger creation of deployment database

content: 1.1.28

---

app_data/sheets/contents.json
app_data/sheets/template/component_demo/feat_animated_slides.json
app_data/sheets/template/debug_sync_id.json
config.ts

- add sync and user id template

content: 1.1.29

---

app_data/sheets/contents.json
app_data/sheets/template/component_demo/comp_html.json
app_data/sheets/template/debug_hyperlinks.json
config.ts

- add hyperlinks testing template

content: 1.1.30

---

app_data/sheets/template/debug/debug_dashed_box.json
app_data/sheets/template/debug_hyperlinks.json
config.ts

content: 1.1.33

---

app_data/sheets/contents.json
app_data/sheets/template/debug_override_default.json
app_data/sheets/template/debug_override_override.json
config.ts

content: 1.1.34

---

app_data/sheets/contents.json
app_data/sheets/template/debug/example_calc_split.json
config.ts

Update example for how to work with json fields

content: 1.1.35

---

app_data/sheets/contents.json
app_data/sheets/data_list/debug/debug_nav_list.json
app_data/sheets/template/debug/debug_nav.json
app_data/sheets/template/debug/debug_nav_2.json
app_data/sheets/template/debug/debug_pop_up_dismiss.json
app_data/sheets/template/debug/debug_pop_up_return.json
config.ts

content: 1.1.36

---

app_data/sheets/contents.json
app_data/sheets/data_list/debug/debug_data_list.json
app_data/sheets/data_list/generated/debug_filtered.json
app_data/sheets/data_pipe/debug/debug_data_pipe_translate.json
app_data/sheets/template/component_demo/comp_task_prog_bar_dynamic.json
app_data/sheets/template/debug/debug_data_bottom.json
app_data/sheets/template/debug/debug_data_image.json
app_data/sheets/template/debug/debug_data_middle.json
app_data/sheets/template/debug/debug_data_top.json
config.ts

Sync content
N.B. when running `yarn workflow repo publish` config compile is failing, because of related tasks PR not yet having been merged

content: 1.2.7

---

app_data/sheets/template/app_menu.json
app_data/sheets/template/component_demo/comp_data_items.json
app_data/sheets/template/debug_list_parsing.json
config.ts

content: 1.2.13

---

app_data/sheets/template/app_menu.json
config.ts

content: 1.2.14

---

config.ts

Adds `ios.app_id` and `ios.app_name` properties to config.

content: 1.2.17

---

app_data/sheets/contents.json
app_data/sheets/data_list/generated/example_pipe_appended.json
app_data/sheets/data_pipe/example_pipe/example_data_pipe_append.json
app_data/sheets/template/debug/debug_data_items.json
app_data/sheets/template/debug/debug_data_items_condition.json
app_data/sheets/template/debug/debug_data_items_find_first.json
app_data/sheets/template/debug/debug_data_items_nesting.json
app_data/sheets/template/debug/debug_fullscreen_pop_up_1.json
app_data/sheets/template/debug/debug_fullscreen_pop_up_2.json
app_data/sheets/template/debug/debug_fullscreen_pop_up_3.json
config.ts

content: 1.2.26

---

config.ts

Update config to accommodate RTL language example.
Should be merged after https://github.com/IDEMSInternational/parenting-app-ui/pull/2317

Update config for RTL language

---

app_data/sheets/template/feature_rtl_language.json
app_data/translations/contents.json
app_data/translations/en_rtl/strings.json
app_data/translations_source/translated_strings/translated.en_rtl.json
config.ts

Include `en_rtl` translated string

content: 1.2.30

---

app_data/sheets/template/component_demo/comp_carousel.json
app_data/sheets/template/component_demo/comp_navigation_bar.json
app_data/sheets/template/component_demo/comp_radio_group.json
app_data/sheets/template/component_demo/comp_select_text.json
config.ts
reports/summary.json
reports/summary.md

content: 1.2.46

---

app_data/assets/contents.json
app_data/assets/video/lets_slow_down.mp4
app_data/assets/video/lets_slow_down.srt
app_data/assets/video/lets_slow_down.vtt
app_data/sheets/template/component_demo/comp_carousel.json
app_data/sheets/template/component_demo/comp_radio_group.json
app_data/sheets/template/component_demo/comp_square_button.json
app_data/sheets/template/debug/debug_data_image.json
app_data/sheets/template/debug/debug_dg_center.json
app_data/sheets/template/debug/debug_dg_tool.json
app_data/sheets/template/debug/debug_radio_group.json
app_data/sheets/template/debug/debug_radio_group_image_scale.json
app_data/sheets/template/debug/debug_rounded_corners.json
app_data/sheets/template/debug/debug_set_local_image.json
app_data/sheets/template/debug/debug_video_1.json
config.ts
reports/summary.json
reports/summary.md

content: 1.2.47

---

config.ts

- Updates config to make the `plh_kids_kw` theme available (added in https://github.com/IDEMSInternational/open-app-builder/pull/2468)

content: 1.2.49

---

app_data/sheets/template/feat_app_layout_custom_header.json
app_data/sheets/template/feat_app_layout_no_header.json
app_data/sheets/template/feat_custom_header.json

Content updates to reflect the up-to-date code for https://github.com/IDEMSInternational/open-app-builder/pull/2631

chore: update to reflect updated PR2631

---

config.ts

Update config following https://github.com/IDEMSInternational/open-app-builder/pull/2634

chore: update auth provider config

---

app_data/sheets/template/component_demo/comp_data_items_dev.json
app_data/sheets/template/feature_share.json
config.ts
reports/summary.json
reports/summary.md

Latest content changes. Required for testing https://github.com/IDEMSInternational/open-app-builder/pull/2768 via Android Internal Testing

content: 1.4.5

---

.github/workflows/debug-ios-build.yml
.github/workflows/ios-build.yml

Add support for IOS simulator builds, following work in https://github.com/IDEMSInternational/open-app-builder/pull/2837

feat: reusable ios build

---

app_data/sheets/contents.json
app_data/sheets/data_list/debug_parse_percentage_data.json
app_data/sheets/data_list/scroll_number.json
app_data/sheets/template/component_demo/comp_round_button.json
app_data/sheets/template/debug/feature_action_scroll_top.json
app_data/sheets/template/debug_parse_percentage.json
config.ts
reports/summary.json
reports/summary.md

Latest content, required to merge in advance of [#2949](https://github.com/IDEMSInternational/open-app-builder/pull/2949) in order to compare parsing diffs

content: 1.5.11

---

.github/workflows/content-sync.yml
.github/workflows/get-vars.yml
actions.env

updated content sync action for testing

updated actions

---

app_data/sheets/contents.json
app_data/sheets/data_list/debug_parse_percentage_data.json
app_data/sheets/template/debug/debug_nested_var_alt_child.json
app_data/sheets/template/debug/debug_nested_var_alt_parent.json
app_data/sheets/template/debug/debug_nested_var_emit_child.json
app_data/sheets/template/debug/debug_nested_var_emit_grand.json
app_data/sheets/template/debug/debug_nested_var_emit_parent.json
app_data/sheets/template/debug/feature_action_scroll_top.json
app_data/sheets/template/debug_concatenation.json
app_data/sheets/template/debug_parse_percentage.json
config.ts
reports/summary.json
reports/summary.md

Latest content merge (to help compare diffs for upcoming https://github.com/IDEMSInternational/open-app-builder/pull/2948)

content: 1.6.0

---

app_data/sheets/contents.json
app_data/sheets/template/component_demo/comp_image.json
app_data/sheets/template/debug/debug_parent_group_parents.json
app_data/sheets/template/debug/debug_shared_parent_group.json
app_data/sheets/template/debug_action_list_var.json
app_data/sheets/template/example/example_row_value_transform.json
app_data/sheets/template/feature/feat_notification_actions.json
app_data/sheets/template/feature_parent_point_box.json
config.ts
reports/summary.json
reports/summary.md

Content sync using parser changes from PR https://github.com/IDEMSInternational/open-app-builder/pull/3040

content: 1.7.3

---

config.ts

Update deprecated config property

content: 1.7.7

---

app_data/assets/contents.json
app_data/assets/images/icons/expand_circle_right.svg
app_data/assets/images/icons/lock.svg
app_data/sheets/contents.json
app_data/sheets/data_list/component_demo/module_data.json
app_data/sheets/data_list/task_cards_data_plh.json
app_data/sheets/template/component_demo/comp_apple_sign_in_button.json
app_data/sheets/template/component_demo/comp_google_sign_in_button.json
app_data/sheets/template/component_demo/comp_plh_progress_path.json
app_data/sheets/template/component_demo/eg_plh_module_list_item.json
app_data/sheets/template/debug/debug_remote_assets.json
app_data/sheets/template/debug/example_login_page.json
config.ts
reports/summary.json
reports/summary.md

content: 1.7.10
